### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by yiiTT** [acrcloud/acrcloud_sdk_golang#1]
Solution: add 'libacrcloud_extr_tool.so' to LD_LIBRARY_PATH folder or add acrcloud to LD lib path.
`export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/go/src/github.com/acrcloud/acrcloud_sdk_golang/linux/x86-64/acrcloud` (path to acrcloud/acrcloud_sdk_golang's folder containing libacrcloud_extr_tool.so)

---
Created new golang docker and tried to run test file, but encountered `error while loading shared libraries: libacrcloud_extr_tool.so`

```
root@537b62d966eb:/go/src/github.com/acrcloud/acrcloud_sdk_golang/linux/x86-64# go run -work -x test.go
WORK=/tmp/go-build967875791
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile command-line-arguments=/root/.cache/go-build/3c/3cfac52a08ee9e063490f7f08421c8a5c98cf26d162d730ab425e3f6317f4185-d
packagefile _/go/src/github.com/acrcloud/acrcloud_sdk_golang/linux/x86-64/acrcloud=/root/.cache/go-build/cf/cfe4082c6ef39a7335280d276ecaa403961fbf7c0773842374424b47d993ab2a-d
packagefile fmt=/usr/local/go/pkg/linux_amd64/fmt.a
*** more packagefiles ***
packagefile vendor/golang_org/x/crypto/poly1305=/usr/local/go/pkg/linux_amd64/vendor/golang_org/x/crypto/poly1305.a
packagefile vendor/golang_org/x/text/transform=/usr/local/go/pkg/linux_amd64/vendor/golang_org/x/text/transform.a
EOF
mkdir -p $WORK/b001/exe/
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/test -importcfg $WORK/b001/importcfg.link -s -w -buildmode=exe -buildid=jkMr9wpmSoZchpKMksU6/vqNN2oBeSiyn3SURg3Hx/jYvg3kfLO90lKiBM8Ozz/jkMr9wpmSoZchpKMksU6 -extld=gcc /root/.cache/go-build/3c/3cfac52a08ee9e063490f7f08421c8a5c98cf26d162d730ab425e3f6317f4185-d
$WORK/b001/exe/test
/tmp/go-build967875791/b001/exe/test: error while loading shared libraries: libacrcloud_extr_tool.so: cannot open shared object file: No such file or directory
exit status 127
```

**Comment by qiuxuewen** [comment]
> Created new golang docker and tried to run test file, but encountered `error while loading shared libraries: libacrcloud_extr_tool.so`
> 
> ```
> root@537b62d966eb:/go/src/github.com/acrcloud/acrcloud_sdk_golang/linux/x86-64# go run -work -x test.go
> WORK=/tmp/go-build967875791
> mkdir -p $WORK/b001/
> cat >$WORK/b001/importcfg.link << 'EOF' # internal
> packagefile command-line-arguments=/root/.cache/go-build/3c/3cfac52a08ee9e063490f7f08421c8a5c98cf26d162d730ab425e3f6317f4185-d
> packagefile _/go/src/github.com/acrcloud/acrcloud_sdk_golang/linux/x86-64/acrcloud=/root/.cache/go-build/cf/cfe4082c6ef39a7335280d276ecaa403961fbf7c0773842374424b47d993ab2a-d
> packagefile fmt=/usr/local/go/pkg/linux_amd64/fmt.a
> *** more packagefiles ***
> packagefile vendor/golang_org/x/crypto/poly1305=/usr/local/go/pkg/linux_amd64/vendor/golang_org/x/crypto/poly1305.a
> packagefile vendor/golang_org/x/text/transform=/usr/local/go/pkg/linux_amd64/vendor/golang_org/x/text/transform.a
> EOF
> mkdir -p $WORK/b001/exe/
> cd .
> /usr/local/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/test -importcfg $WORK/b001/importcfg.link -s -w -buildmode=exe -buildid=jkMr9wpmSoZchpKMksU6/vqNN2oBeSiyn3SURg3Hx/jYvg3kfLO90lKiBM8Ozz/jkMr9wpmSoZchpKMksU6 -extld=gcc /root/.cache/go-build/3c/3cfac52a08ee9e063490f7f08421c8a5c98cf26d162d730ab425e3f6317f4185-d
> $WORK/b001/exe/test
> /tmp/go-build967875791/b001/exe/test: error while loading shared libraries: libacrcloud_extr_tool.so: cannot open shared object file: No such file or directory
> exit status 127
> ```

You need to put "libacrcloud_extr_tool.so" in the same directory as "test.go".

**Comment by yiiTT** [comment]
That does not seem to fix the problem, still getting `error while loading shared libraries` with "libacrcloud_extr_tool.so" copied into dir with "test.go" with both `go run` and `go build`.

**Comment by yiiTT** [comment]
Looks like adding the lib to a "LD_LIBRARY_PATH" folder will make the test run however the dynamic link does not work with both `go run test.go` and `go build test.go && ./test`
```
/*
#cgo CFLAGS: -I.
#cgo LDFLAGS: -L. -lacrcloud_extr_tool -lpthread
#include <stdio.h>
#include <stdlib.h>
#include "dll_acr_extr_tool.h"
*/
```
go env
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build661614611=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by qiuxuewen** [comment]
Yes, you need to add the path of "libacrcloud_extr_tool.so" to "LD_LIBRARY_PATH".

**Comment by qiuxuewen** [comment]
But you can run “test.go” as follows.

acrcloud@acrcloud-PowerEdge-R720:~/go_sdk/test$ ls
acrcloud  libacrcloud_extr_tool.so  query0017.wav  test.go
acrcloud@acrcloud-PowerEdge-R720:~/go_sdk/test$ **go run test.go query0017.wav** 
202044
2019-01-08 15:39:46.229676712 +0800 CST
798
2019-01-08 15:39:47.027243418 +0800 CST
{"status":{"msg":"Success","code":0,"version":"1.0"},"metadata":{"timestamp_utc":"2019-01-08 07:39:47","humming":[{
