### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by DMEvanCT** [acrcloud/acrcloud_sdk_golang#2]
This is great but there is no documentation. We may want to speed our lambdas up by moving from Python to go it would be nice to have the docs.

**Comment by owlwang** [comment]
Hi, DMEvanCT

We have updated our documentation here
https://docs.acrcloud.com/sdk-reference/backend-sdk/go

If you encounter any problems with using it, please feel free to contact us (support@acrcloud.com) for faster support.
